format = """
    $directory $character
$line_break
$line_break""" 

right_format = """
$username\
$hostname\
$git_state\
$git_status\
${custom.gitonly}\
${custom.jj}\
$cmd_duration\
$line_break\
$python\
"""

add_newline = true

palette = "custom_colors"

[palettes.custom_colors]
primary = "Bright-Green"
secondary = "Blue"
accent = "Bright-Green"

[character]
success_symbol = "[>](bold primary)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[directory]
format = "[$path]($style) "
style = "primary"
read_only = " 󰌾"
home_symbol = "~"
truncation_length = 0  # Zeigt vollen Pfad, setze auf 3 für kürzeren Pfad
truncate_to_repo = true  # false = voller Pfad, true = nur ab git repo root

[git_branch]
disabled = true
format = "[$symbol](secondary)[$branch]($style)"
symbol = " "
style = "primary"

[git_status]
disabled = true
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

# Stattdessen eigenes Git-Only-Modul
[custom.gitonly]
command = "git rev-parse --abbrev-ref HEAD"
when = "! jj root >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1"
format = "[$symbol($output)](bold blue) "
symbol = "   "

[cmd_duration]
format = "[$duration]($style) "
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
symbol = " "
style = "bright-black"

[custom.jj]
command = "prompt"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = true
style = "primary"

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "


[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "


[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "


[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "


