
# Text that will be printed between each Module.
module_separator = " "
# Controls whether colors are reset at the end of output.
# Try this if your prompt displays a blank space at the end.
# reset_color = true
# Timeout after wich the process is teminated.
# timeout = 1000

# Controls the behaviour of the bookmark finding algorythm.
[bookmarks]
# Controls how far we are looking back to find bookmarks.
exclude = []
# Controls how far we are looking back to find bookmarks.
# search_depth = 0

[[module]]
# Prints information about bookmarks in the working copies ancestors.
type = "Bookmarks"
# Text that will be rendered between each bookmark.
separator = " "
# Color the text will be rendered in. One of Black, Red, Green, Yellow, Blue, Magenta, Cyan, White,
# BrightBlack, BrightRed, BrightGreen, BrightYellow, BrightBlue, BrightMagenta, BrightCyan, BrightWhite
color.TrueColor = [0, 255, 175]
# True RGB Color can also be used like this. Do not use both color and color.TrueColor at the same time!
# color.TrueColor = [255, 255, 255]
# Text background color. Can also be TrueColor.
# bg_color.TrueColor = [255, 255, 85]
# A suffix that will be printed when the given bookmark is behing the working copy.
behind_symbol = "⇡"
# Maximum amout of bookmarks that will be rendered.
# max_bookmarks = 1
# Maximum length the bookmark name will be truncated to.
# max_length = 10
# Surround the bookmark names with double-quotes
# surround_with_quotes = true

[[module]]
# Prints the working copies commit text
type = "Commit"
# Maximum length the commit text will be truncated to.
max_length = 24
color.TrueColor = [0, 255, 175]
# bg_color.TrueColor = [255, 255, 85]
# default text if the commit description is not set
# empty_text = "(no description set)"
# Surround the commit text with double-quotes
# surround_with_quotes = true

[[module]]
# Prints a warning if the working copy contains any conflicts, is divergent or hidden
type = "State"
# Text that will be printed between each Warning.
separator = " "

[module.conflict]
text = "(CONFLICT)"
color.TrueColor = [255, 85, 85]
# bg_color.TrueColor = [255, 255, 85]

[module.divergent]
text = "(DIVERGENT)"
color.TrueColor = [85, 255, 255]
# bg_color.TrueColor = [255, 255, 85]

[module.hidden]
text = "(HIDDEN)"
color.TrueColor = [255, 255, 85]
# bg_color.TrueColor = [255, 255, 85]

[module.immutable]
disabled = false
text = "(IMMUTABLE)"
color.TrueColor = [255, 255, 85]

[module.empty]
disabled = false
text = "(EMPTY)"
color.TrueColor = [0, 255, 175]

[[module]]
# Prints the amount of changes in the working copy
type = "Metrics"
color.TrueColor = [0, 255, 175]
# bg_color.TrueColor = [255, 255, 85]
# Controls how the changes are rendered, use {added}, {removed} and {changed} to render the number of changes.
template = "[{changed} {added} {removed}]"

[module.changed_files]
# Controlls how the number of changed files is rendered.
# suffix = ""
# prefix = ""
color.TrueColor = [255, 255, 85]
# bg_color.TrueColor = [255, 255, 85]

[module.added_lines]
# Controlls how the number of changed files is rendered.
prefix = "+"
# suffix = ""
color.TrueColor = [0, 255, 175]
# bg_color.TrueColor = [255, 255, 85]

[module.removed_lines]
# Controlls how the number of removed lines is rendered.
prefix = "-"
# suffix = ""
color.TrueColor = [255, 85, 85]
# bg_color.TrueColor = [255, 255, 85]

